#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

droplets=$(instances)
selected=$(cat $AXIOM_PATH/selected.conf)
quiet=false
query=""
args=""
cache=false
command="$1"

for var in "$@"
do
	if [ "$var" == "--cache" ]
    then
		cache=true
    fi
done

if [ $cache != "true" ]
then
	generate_sshconfig
fi

if [ ! -z "$2" ]
then
    query="$2"
    if [[ "$query" =~ "*" ]]
    then
		selected=$(query_instances_cache "$query")
    else
    	selected="$query"
    fi
fi

if [[ ! -z "$3" && "$3" != "--cache" ]]
then
    quiet=true
fi

if [ ! -z "$4" ]
then
	if [[ "$4" == "-t" ]]
	then
		args="-t"
	fi
fi

if [ -z "$1" ]
then
    echo "Provide an argument n00b!"
    exit 0
fi

total=$(echo $selected | tr ' ' '\n' | wc -l | awk '{ print $1 }')

i=1
for name in $selected
do
    if [[ "$quiet" != "true" ]]
    then
        echo -e "${BWhite}Executing inline on $name...${Color_Off}"
        echo -n -e "${Blue}" 
    fi

    cmd="$1"
    rendered=$(echo $cmd | sed "s/\$i/$i/g" | sed "s/\$name/$name/g" | sed "s/\$total/$total/g")

    ssh -F "$AXIOM_PATH"/.sshconfig -o StrictHostKeyChecking=no "$name" $args "$rendered"

    if [[ "$quiet" != "true" ]]
    then
        echo -n -e "${Color_Off}" 
        echo -e "${BGreen}Execute on $name' successful!${Color_Off}" 
    fi
    i=$((i+1))
done

