#!/bin/bash 
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/system-notification.sh"

builder="$(jq -r '.provider' "$AXIOM_PATH"/axiom.json)"
provisioner="full"
start_time=$(date +%s)

if [ ! -z $1 ]
then
	provisioner="$1"
fi

prov_path="$AXIOM_PATH/images/provisioners/$provisioner.json"
builder_path="$AXIOM_PATH/images/builders/$builder.json"

if [ ! -f "$prov_path" ]
then
	echo -e "${Red}Error: unfortunately, there is no $provisioner_path...${Color_Off}"
	exit
fi
	
if [ ! -f "$builder_path" ]
then
	echo -e "${Red}Error: unfortunately, there is no $builder_path...${Color_Off}"
	exit
fi

image_path="$AXIOM_PATH/images/axiom.json"
"$AXIOM_PATH"/interact/generate_packer "$builder" "$provisioner"

if [[ ! -f "$AXIOM_PATH/configs/authorized_keys" ]]
then
	echo -e "${BRed}You have no authorized keys file at $AXIOM_PATH/configs/authorized_keys"
	echo -e  "Please run 'cat ~/.ssh/id_rsa.pub >> $AXIOM_PATH/configs/authorized_keys' and re-run axiom-build"
	echo -e "You may need to generate a fresh SSH keypair...${Color_Off}"
	exit
fi

cd "$AXIOM_PATH"/ || exit

echo -e "${BWhite}Building image $provisioner for provider $builder... This can take up to 25 minutes so please be patient!\nOcassionally this will fail, we  don't know why, but it should auto-restart.${Color_Off}"
if packer build -var-file "$AXIOM_PATH"/axiom.json -var "variant=$provisioner" "$image_path";
then
	end_time=$(date +%s)
	seconds="$(expr $end_time - $start_time)"
	time=""
		
	if [[ "$seconds" -gt 59 ]]
	then
		minutes=$(expr $seconds / 60)
		time="$minutes minutes"
	else
		time="$seconds seconds"
	fi

    echo -e "${BGreen}Your build completed successfully in $time !${Color_Off}"
    echo -e "${Green}To initialize an instance, run axiom-init${Color_Off}"
	  "$AXIOM_PATH"/interact/axiom-prune
    "$NOTIFY_CMD" "Axiom Info" "Build completed successfully!"
else
    echo -e "${BRed}Your build failed :( Please take a look at the errors!${Color_Off}"
    echo -e "${Blue}Builds may fail every now and then, there are some known bugs in Ubuntu Server that cause this."
	  echo -e "Im sorry, but it just fails sometimes, just sit back and relax and we'll try again until  it works ;)${Color_Off}"
    "$NOTIFY_CMD" "Axiom Info" "Build failed :("
    "$AXIOM_PATH"/interact/axiom-build
fi


