#!/usr/bin/env bash

###################################################################
# Title	: axiom-power                                                                                             
# Author : 0xtavian                                                
# Github : https://github.com/0xtavian                                           
###################################################################

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
source "$AXIOM_PATH/interact/includes/system-notification.sh"
begin=$(date +%s)
start="$(pwd)"
BASEOS="$(uname)"
account_path=$(ls -la $AXIOM_PATH/axiom.json | rev | cut -d " " -f 1 | rev)
accounts=$(ls -l "$AXIOM_PATH/accounts/" | grep "json" | grep -v 'total ' | awk '{ print $9 }' | sed 's/\.json//g')
current=$(ls -lh ~/.axiom/axiom.json | awk '{ print $11 }' | tr '/' '\n' | grep json | sed 's/\.json//g') > /dev/null 2>&1


function usage() {
  cat << EOF
  Usage: axiom-power on 'rez\*'
  Examples:
  on                             Power on instance by instance name
  off                           Power off instance by instance name 
  reboot                           Reboot instance by instance name
  help | --help | -h                           Print this help menu
EOF
exit
}

###########################################################################################################
# Declare defaut variables
on=false
help=true
off=false
reboot=false

# Parse command line arguments 
#
i=0
for arg in "$@"
do
    i=$((i+1))
    if [[  ! " ${pass[@]} " =~ " ${i} " ]]; then
        set=false
        if [[ "$i" == 1 ]]; then
            input="$1"
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "on" ]]; then
            n=$((i+1))
            on=true
            instance=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "off" ]]; then
            n=$((i+1))
            off=true
            instance=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "reboot" ]]; then
            n=$((i+1))
            reboot=true
            instance=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] || [[ "$arg" == "help" ]]; then
            usage
            exit
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "--debug" ]]; then
            debug="true"
            set=true
            pass+=($i)
        fi
        if  [[ "$set" != "true" ]]; then
            args="$args $arg"
        fi

    fi
done

# Display Help Menu
#
if [[ "$@" == "--help" ]] || [[ "$@" == "-h" ]] || [[ "$@" == "" ]] || [[ "$@" == "help" ]]; then
usage
exit
fi


# Power Off Snapshots
#
if [[ "$off" == "true" ]]; then
echo -e "Powering off instance: $instance"
for i in $(query_instances "$@" | sort -u | tr ' ' '\n'); do poweroff $i; done
fi

if [[ "$on" == "true" ]]; then
echo -e "Powering on instance: $instance"
for i in $(query_instances "$@" | sort -u | tr ' ' '\n'); do poweron $i; done
fi

if [[ "$reboot" == "true" ]]; then
echo -e "Rebooting instance: $instance"
for i in $(query_instances "$@" | sort -u | tr ' ' '\n'); do reboot $i; done 
#reboot $instance
fi
