#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

accounts=$(ls -l "$AXIOM_PATH/accounts/" | grep "json" | grep -v 'total ' | awk '{ print $9 }' | sed 's/\.json//g')
current=$(ls -lh ~/.axiom/axiom.json | awk '{ print $11 }' | tr '/' '\n' | grep json | sed 's/\.json//g')

if [ ! -z "$1" ]
then
	path="$AXIOM_PATH/accounts/$1.json"
	if [[ -f "$path" ]]
	then
		echo -e "${BWhite}Selecting $1...${Color_Off}"
		rm "$AXIOM_PATH/axiom.json"
		ln -s "$AXIOM_PATH/accounts/$1.json" "$AXIOM_PATH/axiom.json"	
		provider="$(cat "$AXIOM_PATH/axiom.json" | jq -r '.provider')"
		$AXIOM_PATH/interact/axiom-provider "$provider"

        if [[ "$provider" == "do" ]];
        then
            token="$(jq -r '.do_key' "$AXIOM_PATH"/accounts/"$1".json)"
            doctl auth init -t "$token" | grep -vi "using token"
        fi

        if [[ "$provider" == "ibm" ]]; 
        then
            token="$(jq -r '.ibm_cloud_api_key' "$AXIOM_PATH"/accounts/"$1".json)"
            ibmcloud login --apikey "$token"

			if [[ ! -f "$HOME/.packer.d/plugins/packer-builder-ibmcloud" ]]; then
				echo -e "${Red}It seems that you don't have the packer plugin for ibm cloud?${Color_Off}"
				echo -n -e "${Blue}Would you like me to install it for you? (https://github.com/pry0cc/packer-plugin-ibmcloud):\n y/n >> ${Color_Off}"
				read ans

				if [[ "$ans" == "y" ]]; then
					os="$(uname -s | tr '[:upper:]' '[:lower:]')"
					mkdir -p ~/.packer.d/plugins/
					wget -O ~/.packer.d/plugins/packer-builder-ibmcloud "https://raw.githubusercontent.com/pry0cc/packer-plugin-ibmcloud/master/output/packer-builder-ibmcloud-$os"
					chmod +x ~/.packer.d/plugins/packer-builder-ibmcloud
				fi
			fi

        fi

		echo -e "${Green}Selected $1 successfully${Color_Off}"
	else
		echo -e "${Red}Account name not present${Color_Off}"
	fi
else
	echo -e "${BWhite}Available Accounts${Color_Off}"
	echo -n -e "${Blue}"
	for account in $accounts
	do
		if [[ $account == $current ]]
		then
			echo "* $account"
		else
			echo "  $account"
		fi
	done
	echo -n -e "${Color_Off}"
fi
