#!/usr/bin/env bash

Color_Off='\033[0m'       # Text Reset
Red='\033[0;31m'  

if [ -z "$1" ]
then

	echo -e "${Red}No instance supplied, use * if you want to delete all instances...${Color_Off}"
    exit
fi

force=false

if [ ! -z "$2" ]
then
    if [[ "$2" == "-f" ]]
    then
#	    echo -e "${Blue}Force delete enabled...${Color_Off}"
        force=true
    fi
fi

delete_instance() {
    name="$1"
    force="$2"

    if [ "$force" == "true" ]
        then
        doctl compute droplet delete -f "$name"
    else
        doctl compute droplet delete "$name" 
    fi

}

query="$1"
droplets=$(doctl compute droplet list -o json)
selected=""

if [[ $query =~ "*" ]]
then
    selected=$(echo $droplets | jq -r '.[].name' | grep -E "$query")
else
    selected=$(echo $droplets | jq -r '.[].name' | grep -w "$query")
fi

total=$(echo $selected | tr ' ' '\n' | wc -l | awk '{ print $1 }')
chars=$(echo $selected | wc -c | awk '{ print $1 }')
if [ $total -eq 1 ]
then
    if [ $chars -lt 2 ]
    then
	    echo -e "${Red}Instance does not exist..${Color_Off}"
        exit
    fi
    
    selected=$(echo $droplets | jq -r '.[].name' | grep -w "$query")
	
    echo -e "${Red}Deleting '$selected'...${Color_Off}"
    delete_instance "$selected" "$force"
fi
if [ $total -gt 1 ]
then
    i=1
    for name in $selected
    do
	    echo -e "${Red}Deleting '$name'...${Color_Off}"
        delete_instance "$name" "$force" &
        sleep 0.3

        i=$((i+1))
    done
fi
