#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

#droplets=$(instances)

echo -n "" > $AXIOM_PATH/.sshconfig

query_instances 


for name in $(echo "$droplets" | jq -r '.[].name')
do 
	ip=$(echo "$droplets" | jq -r ".[] | select(.name==\"$name\") | .networks.v4[].ip_address")
	echo -e "Host $name\n\tHostName $ip\n\tUser op\n\tPort 2266\n" >> $AXIOM_PATH/.sshconfig
done



scp -r -o StrictHostKeyChecking=no -F $AXIOM_PATH/.sshconfig "$@"
