#!/bin/bash

echo "Hello! Welcome to Axiom configuration :)"
echo "To begin, I will ask you a few questions"
echo "Press enter to continue"
read
if [ ! -d ~/.axiom ]
then
    git clone https://github.com/pry0cc/axiom ~/.axiom
else
    cd ~/.axiom && git pull
fi
echo "What is your DigitalOcean API key? "
echo -n "Key >> "
read do_key
echo "Setting up doctl!..."
doctl auth init -t $do_key
echo "What would you like to pick for region? nyc3, sfo2 <-- this one is best"
echo -n "Region >> "
read region
echo "What domain do you use?"
echo -n "Domain >> "
read domain
#echo "What is your Hunter key? (optional)"
#echo -n "Key >> "
hunter_key=""
size="s-1vcpu-1gb"

if [ -f ~/.ssh/id_rsa.pub ]
then
    echo "Detected SSH public key, would you like me to install this for your axiom setup? y/n"
    read ans
    if [ $ans == "y" ]
    then
        cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys
    fi
else
    echo "No SSH public key detected, would you like to generate a fresh pair? y/n"
    read ans
    if [ $ans == "y" ]
    then
        ssh-keygen
        cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys
    fi
fi

echo "Now to deps! Please wait :)"
OS=$(lsb_release -i | awk '{ print $3 }')

if [ $OS == "Arch" ]
then
    echo "Congrats, you run arch..."
    echo "Ok so you need doctl - so get that from the AUR :) You're smart! You installed arch!"
    sudo pacman -S fzf packer jq
elif [ $OS == "Ubuntu" ]
then
    sudo wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
    wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/
    sudo apt-get update && sudo apt-get install fzf fonts-powerline
fi

echo "{\"do_key\":\"$do_key\", \"region\":\"$region\", \"domain\":\"$domain\", \"default_size\":\"$size\", \"hunter_key\":\"$hunter_key\"}" | jq > ~/.axiom/axiom.json

echo "Beginning first packer build..."
cd ~/.axiom/
packer build -var-file ~/.axiom/axiom.json ~/.axiom/packer.json
cd
