#!/usr/bin/env bash
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

if [ -z "$1" ]
then
    ans="$(instances | jq -r '.[].name' | fzf)"
    ip="$(instance_ip $ans)"
    scp -P2266 op@"$ip":/home/op/vpn/client.ovpn /tmp/"$ans".ovpn
    sudo openvpn /tmp/"$ans".ovpn
else
    ip="$(instance_ip $1)"
    scp -P2266 op@"$ip:"/home/op/vpn/client.ovpn /tmp/"$1".ovpn
    sudo openvpn /tmp/"$1".ovpn
fi
