#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

instance=$(cat $AXIOM_PATH/profile.json | jq -r '.instance')
ip=$(doctl compute droplet list | grep "$instance" | awk '{ print $3 }')

export DOCKER_HOST=ssh://op@$ip:2266
