#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

instance=$(cat ~/.axiom/profile.json | jq -r '.instance')
box_path="$HOME/.axiom/boxes/$instance"
ip=$(doctl compute droplet list | grep $instance | awk '{ print $3 }')

if [ ! -d $box_path ]
then
	mkdir -p $box_path
	mkdir -p $box_path/work/
fi

files="$(ls $box_path/| wc -l| awk '{ print $1 }')"
if [ "$files" == "0" ]
then
	mkdir -p $box_path/work
fi


if [ "$1" == "--forever" ]
then
	echo -e "${BBlue}Starting sync loop for '$instance'...${Color_Off}"
	while true
	do
		echo -e "${BWhite}Synchronizing '$instance'...${Color_Off}"
		echo -e "${Blue}Pushing...${Color_Off}"
		rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress ~/.axiom/boxes/"$instance"/* op@"$ip":~/
		echo -e "${Blue}Pulling...${Color_Off}"
		rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress --delete --exclude="recon" --exclude="lists" --exclude="c2" --exclude="hashes" --exclude="bin" --exclude="down" --exclude="go"  --exclude=".*" op@"$ip":~/ ~/.axiom/boxes/"$instance"
		sleep 10
	done
else
	echo -e "${BWhite}Synchronizing '$instance'..."
	echo -e "${Blue}Pushing...${Color_Off}"
	rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress ~/.axiom/boxes/"$instance"/* op@"$ip":~/
	echo -e "${Blue}Pulling...${Color_Off}"
	rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress --delete --exclude="recon" --exclude="lists" --exclude="c2" --exclude="hashes" --exclude="bin" --exclude="down" --exclude="go"  --exclude=".*" op@"$ip":~/ ~/.axiom/boxes/"$instance"
fi
