#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White


droplets=$(doctl compute droplet list -o json)
instance=$(cat ~/.axiom/profile.json | jq -r '.instance')
command="$1"

if [ ! -z "$2" ]
then
    instance="$2"
fi

echo -e "${BWhite}Watching '$command' on '$instance'... This command will automatically backup and delete the instance after it detects the command is no longer running...  ${Color_Off}"
command="$1"

exit=1
while [[ "$exit" -gt 0 ]]
do 
	exit=$(axiom-exec "ps cax | pgrep "$command" | wc -l | awk '{ print \$1 }'" "$instance" -q)

	sleep $(expr $RANDOM % 20)
done

echo -e "${BGreen}'$command' has completed! Backing up and deleting '$instance'..."
sleep 5
axiom-backup "$instance"
axiom-rm "$instance" -f
