#!/bin/bash

if [ -z "$1" ] 
then
    ans=$(doctl compute droplet list | awk '{ print $2 }' | grep -v "Name" | fzf)
    ip=$(doctl compute droplet list | grep $ans | awk '{ print $3 }')
	ssh -p2266 op@$ip -t 'ranger'
	rsync -avz -e "ssh -p2266" --progress op@$ip:/home/op/down/ ./down/
else
    ip=$(doctl compute droplet list | grep $1 | awk '{ print $3 }')
	ssh -p2266 op@$ip -t 'ranger'
	rsync -avz -e "ssh -p2266" --progress op@$ip:/home/op/down/ ./down/
fi
