#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

if [[ $# -ne 2 ]]; then
	echo "Usage:"
	echo "axiom-rename current_droplet_name new_droplet_name"
else
	droplet="$1"
	new_name="$2"
	droplet_id=$(instance_id $droplet)
	if [[ -z $droplet_id ]]; then
		echo "Droplet $droplet doesn't exist"
	else
		result=$(doctl compute droplet-action rename $droplet_id --droplet-name $new_name)
	fi
fi
