#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
ssh_config="$AXIOM_PATH/.sshconfig"

use_tmux=false
connected=false
cache=false

for var in "$@"
do
    if [ $var == "--tmux" ]
    then
        use_tmux=true
    fi
	if [ $var == "--cache" ]
	then
		cache=true
	fi
done

instance=""

if [ -z "$1" ] || [ "$1" == "--tmux" ]
then
    instance=$(instance_menu)
else
	instance="$1"
fi

if [ $cache != true ]
then
	generate_sshconfig
fi

if [ $use_tmux == true ]
then
	connected=true
	ssh -F $ssh_config "$instance" -t 'tmux new-session -t main'
fi

if [ $connected == false ]
then
	ssh -F $ssh_config "$instance"
fi

"$AXIOM_PATH/interact/header.sh"
