#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

token=""
region=""
provider=""
size=""
email=""

cpu=""
base_image_id=""
username=""
ibm_cloud_api_key=""

appliance_name=""
appliance_key=""
appliance_url=""

echo -e "${BWhite}Axiom Account Setup${Color_Off}"
echo -e "${Blue}You can use this wizard to add new accounts, once made, use axiom-account to switch between profiles${Color_Off}"
echo -e -n "${Green}Please enter your provider (Default 'do', options: 'gcp', 'ibm'): \n>> ${Color_Off}"
read provider

while [[ "$provider" != "do" ]] && [[ "$provider" != "gcp" ]] && [[ "$provider" != "ibm" ]];
do
    if [[ "$provider" == "" ]]
    then
        echo -e "${Blue}Selected default option 'do'${Color_Off}"
        provider="do"
        break
    fi
    echo -e "${BRed}'$provider' is not a valid provider ${Color_Off}"
    echo -e -n "${Red}Please enter a valid provider 'do','gcp', 'ibm': \n>> ${Color_Off}"
    read provider
done

echo -e -n "${Green}Please enter your token (required): \n>> ${Color_Off}"
if [[ "$provider" == "ibm" ]]; then	
	echo -e -n "${Green}Create an IBM Classic API key (for packer) here: https://cloud.ibm.com/iam/apikeys (required): \n>> ${Color_Off}"
fi
read token

while [[ "$token" == "" ]]
do
    echo -e "${BRed}Please provide a token, your entry contained no input.${Color_Off}"
    echo -e -n "${Green}Please enter your token (required): \n>> ${Color_Off}"
    read token
done


if [[ "$provider" == "ibm" ]]; then	
	echo -e -n "${Green}Create an IBM Cloud API Key (for ibmcli) here: https://cloud.ibm.com/iam/apikeys (required): \n>> ${Color_Off}"
	read ibm_cloud_api_key
fi
echo -e -n "${Green}Please enter your default region: (Default 'sfo2', press enter) \n>> ${Color_Off}"

read region

if [[ "$region" == "" ]]; then
    echo -e "${Blue}Selected default option 'sfo2'${Color_Off}"
    region="sfo2"
fi

echo -e -n "${Green}Please enter your default size: (Default 's-1vcpu-1gb, (2048 for IBM)', press enter) \n>> ${Color_Off}"
read size

if [[ "$size" == "" ]]; then
    echo -e "${Blue}Selected default option 's-1vcpu-1gb'${Color_Off}"
    size="s-1vcpu-1gb"
fi

if [[ "$provider" == "ibm" ]]; then
	echo -e -n "${Green}Please enter amount of CPU Cores: (E.g '2') \n>> ${Color_Off}"
	read cpu

	echo -e -n "${Green}Please enter Ubuntu 20.04 Base Image ID: (Example: 'ec374a70-bb8e-4207-85ba-6a0c36b6022a') \n>> ${Color_Off}"
	read base_image_id

	echo -e -n "${Green}Please enter username (E.g 'SL838382832') \n>> ${Color_Off}"
	read username

fi
 

echo -e -n "${Green}Please enter your GPG Recipient Email (for encryption of boxes): (optional, press enter) \n>> ${Color_Off}"
read email

echo -e -n "${Green}Would you like to configure connection to an Axiom Pro Instance? Y/n (Must be deployed.) (optional, default 'n', press enter) \n>> ${Color_Off}"
read ans

if [[ "$ans" == "Y" ]]; then
    echo -e -n "${Green}Enter the axiom pro instance name \n>> ${Color_Off}"
    read appliance_name

    echo -e -n "${Green}Enter the instance URL (e.g \"https://pro.acme.com\") \n>> ${Color_Off}"
    read appliance_url

    echo -e -n "${Green}Enter the access secret key \n>> ${Color_Off}"
    read appliance_key 
fi

data=""

if [[ "$provider" == "ibm" ]]; then
	data="$(echo "{\"do_key\":\"$token\",\"ibm_cloud_api_key\":\"$ibm_cloud_api_key\",\"region\":\"$region\",\"provider\":\"$provider\",\"default_size\":\"$size\",\"cpu\":\"$cpu\",\"username\":\"$username\",\"base_image_id\":\"$base_image_id\",\"appliance_name\":\"$appliance_name\",\"appliance_key\":\"$appliance_key\",\"appliance_url\":\"$appliance_url\", \"email\":\"$email\"}")"
elif [[ "$provider" == "do" ]]; then
	data="$(echo "{\"do_key\":\"$token\",\"region\":\"$region\",\"provider\":\"$provider\",\"default_size\":\"$size\",\"appliance_name\":\"$appliance_name\",\"appliance_key\":\"$appliance_key\",\"appliance_url\":\"$appliance_url\", \"email\":\"$email\"}")"
fi


echo -e "${BGreen}Profile settings below: ${Color_Off}"
echo $data | jq
echo -e "${BWhite}Press enter if you want to save these to a new profile, type 'r' if you wish to start again.${Color_Off}"
read ans

if [[ "$ans" == "r" ]];
then
    $0
    exit
fi

echo -e -n "${BWhite}Please enter your profile name (e.g 'personal', must be all lowercase/no specials)\n>> ${Color_Off}"
read title

if [[ "$title" == "" ]]; then
    title="personal"
    echo -e "${Blue}Named profile 'personal'${Color_Off}"
fi

echo $data | jq > "$AXIOM_PATH/accounts/$title.json"
echo -e "${BGreen}Saved profile '$title' successfully!${Color_Off}"

$AXIOM_PATH/interact/axiom-account $title
