#!/usr/bin/env bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White

if [ ! -z "$1" ]
then
	case $1 in
	ls*)
		
		if [ ! -z "$2" ]
		then
			echo -e "${BWhite}Domains records for $2${Color_Off}"
			echo -n -e "${Blue}"
			doctl compute domain records list "$2"
		else
			echo -e "${BWhite}Available Domains${Color_Off}"
			echo -n -e "${Blue}"
			doctl compute domain list
		fi
		echo -n -e "${Color_Off}"
		;;
	add*)
		subdomain=$2
		domain=$3
		ip=$4
			
		data=$(doctl compute domain list -o json)
		domains=$(echo $data | jq -r '.[].name' | grep $3 | wc -l | awk '{ print $1}')

		if [ $domains -gt 0 ]
		then
			echo -e "${BWhite}Creating DNS record $2.$3 -> $4... ${Color_Off}"
			doctl compute domain records create $domain --record-type A --record-name $2 --record-data $ip	
		else
			echo -e  "${BRed}Domain doesn't exist${Color_Off}"
		fi
		;;
	rm*)
		subdomain=$2
		domain=$3
		ip=$4
			
		data=$(doctl compute domain list -o json)
		domains=$(echo $data | jq -r '.[].name' | grep $3 | wc -l | awk '{ print $1}')

		if [ $domains -gt 0 ]
		then
			subdomains=$(doctl compute domain records list $3 -o json | jq '.[]')
			exists=$(echo $subdomains | jq -r 'select(.type=="A")' | jq -r '.name' | grep $2 | wc -l | awk '{ print $1 }')
			
			if [ $exists -gt 0 ] 
			then
				echo -e "${BWhite}Deleting DNS record $2.$3... ${Color_Off}"
				id=$(echo $subdomains | jq -r 'select(.type=="A")' | jq "select(.name==\"$2\") | .id")
		
				if [ ! -z $4 ]
				then
					if [ $4 == "-f" ]
					then
						echo -e "${Green}Force delete specified...${Color_Off}"
						doctl compute domain records delete $3 $id -f
					else
						doctl compute domain records delete $3 $id 
					fi
				else
					doctl compute domain records delete $3 $id
				fi
			else
				echo -e "${BRed}Subdomain doesn't exist${Color_Off}"
			fi
		else
			echo -e  "${BRed}Domain doesn't exist${Color_Off}"
		fi
		;;

	*)
		echo "Command '$1' not found..."
		;;
	esac

else
	echo -e "Usage:\n\t axiom-dns ls\n\t axiom-dns ls <domain>\n\t axiom-dns add <subdomain> <domain> <ip>"
fi
