#!/bin/bash

cd ~/.axiom/
packer build -var-file ~/.axiom/axiom.json ~/.axiom/packer.json
if [ "$?" == "0" ]
then
    echo "Your build completed successfully!"
    echo "To initialize an instance, run axiom-init"
	~/.axiom/interact/axiom-prune
    notify-send "Axiom Info" "Build completed successfully!"
else
    echo "Your build failed :( Please take a look at the errors!"
    echo "Builds may fail every now and then, there are some known bugs in Ubuntu Server that cause this."
	echo "Im sorry, but it just fails sometimes, just sit back and relax and we'll try again until  it works ;)"
    notify-send "Axiom Info" "Build failed :("
    ~/.axiom/interact/axiom-build
fi


