#!/bin/bash

echo "random_chain,proxy_dns ,remote_dns_subnet 224,tcp_read_time_out 15000,tcp_connect_time_out 8000,[ProxyList]," | tr ',' '\n' > proxychains.conf

axiom-ls $1 | while read line
do 
	i=$(echo $line | cut -d " " -f 1)
	name=$(echo $line | cut -d " " -f 2)
	ip=$(axiom-ls $name)
	ssh -p2266 -o StrictHostKeyChecking=no -D 808$i op@$ip -N &
	echo "Proxy listener started on 808$i for $name:$i"
	echo "socks5 127.0.0.1 808$i" >> proxychains.conf
done
