#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
source "$AXIOM_PATH/interact/includes/appliance.sh"

(echo "Instance,IP,City,Country,Latitude,Longitude"
for instance in $(cat "$AXIOM_PATH/selected.conf")
do
	ip="$(instance_ip_cache $instance)"
	data="$(curl -s "https://ipinfo.io/$ip")"
	city="$(echo "$data" | jq -r '.city')"
	loc="$(echo "$data" | jq -r '.loc')"
	country="$(echo "$data" | jq -r '.country')"

	echo "$instance,$ip,$city,$country,$loc"
done) 
