#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

gen_name=""

if [ -z $1 ] || [[ $1 =~ "-t" ]] || [[ $1 =~ "time" ]] || [[ $1 =~ "spend" ]]
then
    gen_name="${names[$RANDOM % ${#names[@]} ]}"
else
    if [ ! -z $1 ]
    then
        gen_name="$1"
    fi
fi

spend=false
hours=false
amount=false
prompt=false

for var in "$@"
do
    if [[ "$var" =~ "--spend" ]]
    then
        spend="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        echo -e "${BWhite}Setting spend to \$$spend${Color_Off}"
    fi
    if [[ "$var" =~ "--time" ]]
    then
        hours="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        echo -e "${BWhite}Setting expiry to $hours hours${Color_Off}"
    fi
    if [[ "$var" =~ "-i" ]]
    then
        amount="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        echo -e "${BWhite}Setting number of instances to $amount...${Color_Off}"
    fi
done

if [ "$spend" == "false" ]
then
    echo -e -n "${BWhite}Please enter your desired spend in dollars >> \$${White}"
    read spend
    prompt=true
fi

if [ "$hours" == "false" ]
then
    echo -e -n "${BWhite}Please enter your run time in hours >> ${White}"
    read hours
    prompt=true
fi

if [ "$amount" == "false" ]
then
    echo -e -n "${BWhite}Please enter how many instances you want to run >> ${White}"
    read amount
    prompt=true
fi

sizes=$(instance_sizes)
spend_per_hour=$(bc <<< "scale=2; $spend/$hours")
multi_instance_spend=$(bc <<< "scale=2; $spend_per_hour / $amount")
slug=$(echo $sizes | jq -r ".[] | select(.price_hourly < $multi_instance_spend) | .slug" | tail -n 1)
echo -e "${Green}Calculated your target hourly spend per instance at: \$$multi_instance_spend per hour${Color_Off}"
echo -e "${Green}Calculated your target hourly spend total at: \$$spend_per_hour per hour${Color_Off}"
instance_data=$(echo $sizes | jq ".[] | select(.slug==\"$slug\")")
cores=$(echo $instance_data | jq .vcpus)
mem_big=$(echo $instance_data | jq .memory)
price_hourly=$(echo $instance_data | jq .price_hourly)
mem=$(expr $mem_big / 1024)
disk=$(echo $instance_data | jq .disk)
total=$(bc <<< "scale=2; $price_hourly * $hours * $amount")
echo -e "${BWhite}Selected $slug, with $cores cores, $mem GB of RAM and $disk GB HDD, $price_hourly/h"
echo -e "${BWhite}To run $amount instance/s with the above specs for $hours hours, it would cost a total of \$$total"
echo -e "${Green}Would you like to proceed? [ENTER] ${Color_Off}"

if [ "$prompt" == "true" ]
then
    read
fi

total_spend_per_instance=$(bc <<< "scale=2; $multi_instance_spend * $hours")

expiry=$(bc <<< "scale=2; $hours * 60")
expiry=$(bc <<< "scale=2; $expiry - 8")


for i in $(seq -f "%02g" 1 $amount)
do
   name="$gen_name$i"
   echo -e "${BWhite}Initializing $name for $hours hours... This instance will cost exactly \$$total_spend_per_instance"
   $AXIOM_PATH/interact/axiom-init $name --quiet --size=$slug --expire=$expiry &
   sleep 0.3
done

secs=$((120))
while [ $secs -gt 0 ]; do
    echo -ne ">> T-Minus $secs to fleet $gen_name initialization...\033[0K\r"
    sleep 1
    : $((secs--))
done

echo -e "${BGreen}Fleet started succesfully! All instances will automatically implode after $expiry minutes or $hours hours. To extend the lifetime on an instance, set-expiry.sh \"10 hours\" etc.${Color_Off}" 
