#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

if [ ! -z "$1" ]
then
	case $1 in
	ls*)
		
		if [ ! -z "$2" ]
		then
			echo -e "${BWhite}Domains records for $2${Color_Off}"
			echo -n -e "${Blue}"
			list_dns "$2"
		else
			echo -e "${BWhite}Available Domains${Color_Off}"
			echo -n -e "${Blue}"
			list_domains
		fi
		echo -n -e "${Color_Off}"
		;;
	add*)
		subdomain=$2
		domain=$3
		ip=$4
			
		data=$(list_domains_json)
		domains=$(echo $data | jq -r '.[].name' | grep $3 | wc -l | awk '{ print $1}')

		if [ $domains -gt 0 ]
		then
			echo -e "${BWhite}Creating DNS record $2.$3 -> $4... ${Color_Off}"
            add_dns_record $subdomain $domain $ip
		else
			echo -e  "${BRed}Domain doesn't exist${Color_Off}"
		fi
		;;
	rm*)
		subdomain=$2
		domain=$3
		ip=$4
			
		data=$(list_domains_json)
		domains=$(echo $data | jq -r '.[].name' | grep $3 | wc -l | awk '{ print $1}')

		if [ $domains -gt 0 ]
		then
			subdomains=$(list_subdomains $3)
			exists=$(echo $subdomains | jq -r 'select(.type=="A")' | jq -r '.name' | grep $2 | wc -l | awk '{ print $1 }')
			
			if [ $exists -gt 0 ] 
			then
				echo -e "${BWhite}Deleting DNS record $2.$3... ${Color_Off}"
				id=$(echo $subdomains | jq -r 'select(.type=="A")' | jq "select(.name==\"$2\") | .id")
		
				if [ ! -z $4 ]
				then
					if [ $4 == "-f" ]
					then
						echo -e "${Green}Force delete specified...${Color_Off}"
                        delete_record_force $3 $id
					else
                        delete_record $3 $id
					fi
				else
                    delete_record $3 $id
				fi
			else
				echo -e "${BRed}Subdomain doesn't exist${Color_Off}"
			fi
		else
			echo -e  "${BRed}Domain doesn't exist${Color_Off}"
		fi
		;;

	*)
		echo "Command '$1' not found..."
		;;
	esac

else
	echo -e "Usage:\n\t axiom-dns ls\n\t axiom-dns ls <domain>\n\t axiom-dns add <subdomain> <domain> <ip>"
fi
