#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

# Host Options
targets_infile=""
selected_module="masscan"
query="$1"
src_prefix="$AXIOM_PATH/tmp/$RANDOM"
outfile="$(echo "$query" | sed 's/\*//g')-$(date +%s).txt"
user_args=""
ports=""
# Set user input
for var in "$@"
do
	if [[ "$var" =~ "-p" ]]
	then
		ports=$(echo $var | sed 's/-p//g')
	elif [[ "$var" =~  "-iL=" ]]
	then
		targets_infile=$(echo "$var" | cut -d "=" -f2)
	elif  [[ "$var" =~ "-m=" ]]
	then
		s=$(echo "$var" | cut -d "=" -f2)
		if [ -f "$AXIOM_PATH/interact/modules/$s.json" ]
		then
			selected_module="$s"
		else
			echo -e "${BRed}Module: '$s' does not exist, valid modules are:${Color_Off}"
			echo -e -n "${Blue}"
			ls "$AXIOM_PATH/interact/modules/" | sed 's/\.json//g'
			echo -e -n "${Color_Off}"
			exit
		fi
	elif  [[ "$var" =~ "-o=" ]]
	then
		outfile=$(echo "$var" | cut -d "=" -f2)
	else
		if [[ "$var" !=  "$query" ]]	
		then
			user_args="${user_args} ${var}"
		fi
	fi
done

#Load from the module
module="$AXIOM_PATH/interact/modules/$selected_module.json"
cmd=$(jq -r '.command'  $module)
box_infile=$(jq -r '.box_infile'  $module)
box_outfile=$(jq -r '.box_outfile'  $module)
outdir=$(jq -r '.output_dirs'  $module)
outformat=$(jq -r '.output_format' $module) 
ext=$(jq -r '.output_ext' $module)

if [ ! "$ports" ]
then
	ports=$(jq -r '.default_ports'  $module)
fi
args="$(jq -r '.default_args'  $module)"

if [ "$user_args" ]
then
	args="$user_args"
fi


if [[ ! -f $targets_infile ]]
then
	if [[ "$box_infile" ]]
	then
		# This checks if the json  parameter is present,  if they dont specify it, we dont have to ask...
		echo -e "${BRed}Please specify a file with -iL=targets.txt${Color_Off}"
		exit
	fi
fi
instances=$(query_instances "$1")

echo -e "${BWhite}Starting axiom-scan with module '$selected_module' for fleet '$query'${Color_off}"

if [ "$instances" ]
then
	if [[ "$box_infile" ]]
	then
		echo -e "${Blue}Splitting file $targets_infile across all instances...${Color_Off}"
		src_prefix=$(lsplit $targets_infile "$instances")
		axiom-scp "$src_prefix/\$name.txt" "$query:$box_infile"
	else
		mkdir -p $src_prefix
	fi
	
	cmd_rendered=$(echo $cmd | sed "s/\$ports/$ports/g" | sed "s/\$args/$args/g" | sed "s/\$infile/$box_infile/g"  | sed "s/\$outfile/$box_outfile/g")
	echo  $instances | tr ' ' '\n' > $src_prefix/hosts.txt
	
	total=$(wc -l $src_prefix/hosts.txt | awk '{ print $1 }')
	echo -e "${Blue}Launching $selected_module on fleet '$query'...${Color_Off}"
	ssh_args=""

	if [[ "$selected_module" == "ffuf" ]]
	then
		ssh_args="-t"
	fi
	interlace -tL $src_prefix/hosts.txt -threads $total -c "axiom-exec '$cmd_rendered' '_target_' -q $ssh_args" 
	echo -e "${Blue}Downloading output from fleet '$query'...${Color_Off}"

	rm -rf "$src_prefix"
	mkdir -p "$src_prefix"

	if [ "$outdir" == "true" ]
	then
		# Recursive Directory Download
		axiom-scp "$query:$box_outfile/*" "$src_prefix"
		sleep 1
		mv $src_prefix/output $outfile
		echo -e "${Green}Output saved to $outfile/${Color_Off}"
	else
		axiom-scp "$query:$box_outfile" "$src_prefix/\$name-out.$ext"
		if [[ "$outformat" == "txt" ]] || [[ "$outformat" == "greppable" ]]
		then
			echo -e "${Green}Merging and sorting output...${Color_Off}"
			cat $src_prefix/$query-out.$ext | sort -u > $outfile
			echo -e "${BGreen}File saved to $outfile${Color_Off}"
		elif [[ "$outformat" == "xml" ]];
		then
			"$AXIOM_PATH/interact/merge-xml.py" -d "$src_prefix" -o "$PWD/$outfile"
		fi
	fi

	else
	echo -e "${BRed}No instances in that fleet, use 'axiom-fleet -i=7 -t=2' to spin up a fleet${Color_Off}"
fi


