#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

function help() {
    echo -e "${BWhite}Usage of axiom-fleet${Color_Off}"
    echo -e "Example Usage: ${Blue}axiom-fleet -i=10${Color_Off}"
    echo -e "  -i int"
    echo -e "    How many instances you'd like to spin up"
    echo -e "  -t int"
    echo -e "    Set an expiry time (in hours)."
    echo -e "  --help"
    echo -e "    Display this help menu"
}

gen_name=""
provider="$(jq -r ".provider" "$AXIOM_PATH/axiom.json")"

if [ -z $1 ] || [[ $1 =~ "-i" ]] || [[ $1 =~ "-t" ]] 
then
    gen_name="${names[$RANDOM % ${#names[@]} ]}"
else
    if [ ! -z $1 ]
    then
        gen_name="$1"
    fi
fi

spend=false
hours=false
amount=false
prompt=false
region=false
image=false
cycle_regions=false
region_array=()


for var in "$@"
do
    if [[ "$var" =~ "-t" ]]
    then
        hours="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        #echo -e "${BWhite}Setting expiry to $hours hours${Color_Off}"
    fi
    if [[ "$var" == "-h" ]] || [[ "$var" == "--help" ]];
    then
        help
        exit 0
    fi
    if [[ "$var" =~ "-i" ]]
    then
        amount="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        #echo -e "${BWhite}Setting number of instances to $amount...${Color_Off}"
    fi
    if [[ "$var" =~ "--regions=" ]]
    then
        cycle_regions="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        echo -e "${BWhite}Cycling through following regions:$cycle_regions...${Color_Off}"
        IFS=',' read -r -a region_array <<< "$cycle_regions"
    fi
    if [[ "$var" =~ "--image=" ]]
    then
        image="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        #echo -e "${BWhite}Setting number of instances to $amount...${Color_Off}"
    fi
	if [[ "$var" =~ "-r" ]]
    then
		regions=$(snapshots | jq -r '.[] | select(.name | contains("axiom")) | .name'  | cut -d "-" -f 2 | sort -u)
    fi
done


if [ "$hours" == "false" ]
then
    hours=1
fi

if [ "$amount" == "false" ]
then
	amount=3
fi

echo -e "${BWhite}Initializing new fleet '$gen_name' with $amount instances...${Color_Off}"
sizes=$(instance_sizes)
slug=$(cat $AXIOM_PATH/axiom.json | jq -r .default_size)  >/dev/null 2>&1
#slug="s-1vcpu-1gb"
instance_data=$(echo $sizes | jq ".[] | select(.slug==\"$slug\")") >/dev/null 2>&1

total_spend_per_instance_rounded="0"

if [[ "$instance_data" != "" ]]
then
price_hourly=$(echo $instance_data | jq .price_hourly)
cores=$(echo $instance_data | jq .vcpus)
mem_big=$(echo $instance_data | jq .memory)
mem=$(expr $mem_big / 1024)
disk=$(echo $instance_data | jq .disk)
total=$(bc <<< "scale=2; $price_hourly * $hours * $amount")
total_rounded=$(echo "scale=3; price=$total; scale=2; price/1 " | bc | sed 's/^\./0./')
total_spend_per_instance=$(bc <<< "scale=2; $price_hourly * $hours")
total_spend_per_instance_rounded=$(echo "scale=3; price=$total_spend_per_instance; scale=4; price/1 " | bc | sed 's/^\./0./')
echo -e "${Green}Total estimated cost: \$$total_rounded${Color_Off}"
fi

echo -e "${BWhite}INITIALIZING IN 3 SECONDS, CTRL+C to quit... ${Color_Off}"

expiry=$(bc <<< "scale=2; $hours * 60")
expiry=$(bc <<< "scale=2; $expiry - 8")
time=150

if [[ "$provider" == "ibm" ]]; then
	# IBM IS SUPER SLOW SO ADD 200 seconds to fleets...
	time=350
fi

image_id=""
image_name=""
image="$(jq -r '.image' $AXIOM_PATH/axiom.json)"
region="$(jq -r '.region' $AXIOM_PATH/axiom.json)"

if [[ "$image" != "null" ]]
then
	image_name="$image-$region"
else
	image_name="axiom-$region"
fi

# Basically repeat items, if the fleet is 20 hosts and they only supply 3 regions, loop over them until it reaches 20
total_regions=$(echo "${region_array[@]}" |  tr ' ' '\n' | wc -l | awk '{ print $1 }')
regions_to_cycle=()

if [[ "$cycle_regions" != "false" ]]; then
	
	k=0
	while [[ "$(echo ${regions_to_cycle[@]} | tr ' ' '\n' | wc -l | awk '{ print $1}')" -lt "$amount" ]]
	do
		regions_to_cycle+=("${region_array[k]}")
		if [[ "$k" -lt "$total_regions" ]]; then
			k=$((k+1))
		else
			k=0
		fi
	done
fi

# Remove  null items from array
for i in "${!regions_to_cycle[@]}"; do
  [ -n "${regions_to_cycle[$i]}" ] || unset "regions_to_cycle[$i]"
done

image_id=$(get_image_id "$image_name")

o=0
for i in $(seq -f "%02g" 1 $amount)
do
   time=$((time+2))
   name="$gen_name$i"
   echo -e "${BWhite}Initializing $name for $hours hours... This instance will cost: \$$total_spend_per_instance_rounded"
   args=""
 
	if [[ "$cycle_regions" != "false" ]]; then
		args="--uregion=${regions_to_cycle[o]}"	
	fi
	
   $AXIOM_PATH/interact/axiom-init $name --quiet --size=$slug --expire=$expiry --image_id="$image_id" $args --no-select &
   sleep 0.05
   o=$((o+1))
done

while [ $time -gt 0 ]; do
    echo -ne ">> T-Minus $time to fleet $gen_name initialization...\033[0K\r"
    sleep 1
    : $((time--))
done

$AXIOM_PATH/interact/axiom-select "$gen_name*"

echo -e "${BGreen}Fleet started succesfully! All instances will automatically implode after $expiry minutes or $hours hours. To extend the lifetime on an instance, set-expiry.sh \"10 hours\" etc.${Color_Off}" 
