#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

name=""

if [ -z "$1" ]
then
    name="$(instance_menu)"
else
	name="$1"
fi

vpn_dst="/tmp/$name.ovpn"
#ip="$(instance_ip $name)"
$AXIOM_PATH/interact/axiom-scp "$name":/home/op/vpn/client.ovpn $vpn_dst
sudo openvpn $vpn_dst
