#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

droplets=$(doctl compute droplet list -o json)
instance=$(cat $AXIOM_PATH/profile.json | jq -r '.instance')
command="$1"

if [ ! -z "$2" ]
then
    instance="$2"
fi


if [ -z "$1" ]
then
    echo "Provide an argument n00b!"
    exit 0
fi

selected=$(echo $droplets | jq -r '.[].name' | grep -E "$instance")
total=$(echo $selected | tr ' ' '\n' | wc -l | awk '{ print $1 }')

i=1
for name in $selected
do
    ip=$(echo $droplets | jq -r ".[] | select(.name == \"$name\") | .networks.v4[].ip_address")
    echo -e "${BWhite}Executing inline on $name at $ip ${Color_Off}"
    echo -n -e "${Blue}" 

    

    cmd="$1"
    rendered=$(echo $cmd | sed "s/\$i/$i/g" | sed "s/\$name/$name/g" | sed "s/\$total/$total/g")


    ssh -p2266 -o StrictHostKeyChecking=no op@"$ip" 'tmux new-session -d -t main'
    ssh -p2266 -o StrictHostKeyChecking=no op@"$ip" tmux send-keys "'$rendered' Enter"


    echo -n -e "${Color_Off}" 
    echo -e "${BGreen}Execute on $name' successful!${Color_Off}" 
    i=$((i+1))
done

