#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
ssh_config="$AXIOM_PATH/.sshconfig"

use_tmux=false
use_mosh=false
connected=false
cache=false
just_generate=false
use_clipboard_sync=false

args="-F $ssh_config"

for var in "$@"
do
    if [ $var == "--tmux" ]
    then
        use_tmux=true
    elif [ $var == "--cache" ] 
    then
        cache=true
    elif [ $var == "--just-generate" ]
    then
        just_generate=true
    elif [ $var == "-m" ]
    then
        use_mosh=true
    elif [ $var == "--clipboard-sync" ]
    then
        use_clipboard_sync=true
    else
        args="$args $var"
    fi
done


if [ $cache != true ]
then
	generate_sshconfig
fi

if [ $use_tmux == true ]
then
	args="$args -t 'tmux new-session -t main'"
fi

if [ $use_mosh == true ]
then
	new_args=""

	for i in $args
	do
		if [[ "$i" != "$1" ]]
		then
			new_args="$new_args $i"
		fi
	done
	cmd="mosh --ssh='ssh $new_args' $1 -- tmux attach -t main-15 -d"

	echo $cmd
else
    if [ $use_clipboard_sync == true ]
    then 
        args="$args -R 2489:127.0.0.1:2489"
        start_lemonade_server
    fi
	cmd="ssh $args"
fi

if [ $just_generate == "false" ]
then
	bash -c "$cmd"
fi
"$AXIOM_PATH/interact/header.sh"
