#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

instance="$(selected_instance)"
ip="$(instance_ip $instance)"

export DOCKER_HOST="ssh://op@$ip:2266"
