#!/bin/bash
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White


echo "random_chain,proxy_dns ,remote_dns_subnet 224,tcp_read_time_out 15000,tcp_connect_time_out 8000,[ProxyList]," | tr ',' '\n' > proxychains.conf

data=$(axiom-ls --json)

axiom-ls $1 | while read line
do 
	i=$(echo $line | cut -d " " -f 1)
	name=$(echo $line | cut -d " " -f 2)
	ip=$(echo $data | jq -r ".[] | select(.name == \"$name\") | .networks.v4[].ip_address")
	se=$(seq -f "%02g" $i $i)
	port="50$se"
	ssh -p2266 -o StrictHostKeyChecking=no -D $port op@$ip -N 2>&1 >> /dev/null &
	echo -e "${BWhite}Proxy listener started on $port for $name...${Color_Off}"
	echo "socks5 127.0.0.1 $port" >> proxychains.conf
	sleep 0.6
done

echo "${BGreen}Proxies connected and saved in ./proxychains.conf${Color_Off}"
