#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

echo -e "${BWhite}Axiom Account Setup${Color_Off}"
echo -e "${Blue}You can use this wizard to add new accounts, once made, use axiom-account to switch between profiles${Color_Off}"
account_helpers=$(find "$AXIOM_PATH/interact/account-helpers" | grep "\.sh" | tr '/' ' ' | awk '{ print $NF }' | tr -d '.sh')
account_str=$(echo $account_helpers | sed 's/ /, /g')
echo -e -n "${Green}Please enter your provider ($account_str): \n>> ${Color_Off}"
read provider
provider_path="$AXIOM_PATH/interact/account-helpers/$provider.sh"

while [[ ! -f "$provider_path" ]]; 
do
	echo -e -n "${Green}This is not a valid provider, please enter your a valid provider ($account_str): \n>> ${Color_Off}"
	read provider
	provider_path="$AXIOM_PATH/interact/account-helpers/$provider.sh"
done

bash "$provider_path"
echo -e "${Blue}Now your account is setup, we need to run a build"
echo "A build will take about 25 minutes, spin up a temporary instance, and then snapshot it to use for our future boxes"
echo -e "Starting Build in 5 seconds... Ctrl+C to quit, remember, you can just type axiom-build at any time${Color_Off}"
sleep 5
bash "$AXIOM_PATH/interact/axiom-build"