#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

instances=""
cache=false
args=""

i=0
for var in "$@"
do
    if [ $var == "--cache" ]
	then
		cache=true
	else
		args="$args $var"
	fi
	i=$((i+1))
done

if [ $cache != "true" ]
then
	generate_sshconfig
fi

echo -n "" > $AXIOM_PATH/tmp/cmds.txt

for var in $args
do
	host=$(echo $var | cut -d ":" -f 1)
	if [[ "$host" =~ "*" ]]
	then
		instances=$(query_instances_cache "$host")
		full=$(echo "$var" | sed "s/\$name/$instance/g")
		if [[ "$str" ]]
		then
			str="$str $full"
		else
			str="$full"
		fi

	else
		if [[ "$str" ]]
		then
			str="$str $var"
		else
			str="$var"
		fi
	fi
done

if [ "$instances" ]
then
for instance in $instances
do
line=""
for var in $args
do
	host=$(echo $var | cut -d ":" -f 1)
	str=""
	if [[ "$host" =~ "*" ]]
	then
		full=$(echo "$var" | sed "s/$host/$instance/g"| sed 's/\*//g')
		if [[ "$str" ]]
		then
			str="$str $full"
		else
			str="$full"
		fi
	else
		if [[ "$str" ]]
		then
			str="$str $var"
		else
			str="$var"
		fi
	fi

	str=$(echo $str | sed "s/\$name/$instance/g")

	if [ "$line" ]
	then
		line="$line $str"
	else
		line="$str"
	fi
done
ssh_conf="$AXIOM_PATH/.sshconfig"
cmd="rsync -e 'ssh -o StrictHostKeyChecking=no -F $ssh_conf' -azr --progress $line"
echo "$cmd" >> $AXIOM_PATH/tmp/cmds.txt
#scp -r -o StrictHostKeyChecking=no -F $AXIOM_PATH/.sshconfig $line
done
#sleep 1
echo -e "${BGreen}Running parallel file transfer...${Color_Off}"
interlace -t 0x00sec.org -cL $AXIOM_PATH/tmp/cmds.txt
else
	rsync -e "ssh -o StrictHostKeyChecking=no -F $AXIOM_PATH/.sshconfig"  -avzr --progress $args
fi
