#!/bin/bash

profile=""

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

remove=false

for var in "$@"
do
    if [ $var == "--remove" ]
    then
        remove=true
    fi
done

if [ -z "$1" ] || [ "$1" == "--remove" ] || [ "$1" == "--instance" ]
then
    profile=$(ls $AXIOM_PATH/profiles | cat | fzf)
else
    exists=$(ls $AXIOM_PATH/profiles | cat | grep "\<$1\>" | wc -l | awk '{ print $1 }')
    if [ "$exists" == "1" ]
    then
        profile="$1"
    else
        echo "Profile doesnt exist, launching selector..."
        profile=$(ls $AXIOM_PATH/profiles | cat | fzf)
    fi
fi

instances=$(cat $AXIOM_PATH/selected.conf)
success_command=$(cat $AXIOM_PATH/profiles/$profile/manifest.json | jq -r '.success_message')

for instance in  $instances
do
ip=$(instance_ip $instance)
id="$RANDOM"
filename="/tmp/$id.sh"

if [ $remove == false ]
then
	cat $AXIOM_PATH/profiles/$profile/manifest.json | jq -r '.commands[]' > $filename
elif [ $remove == true ]
	then
	cat $AXIOM_PATH/profiles/$profile/manifest.json | jq -r '.remove_commands[]' > $filename
fi
chmod +x $filename

if [ $remove == false ]
then
	echo -e "${BWhite}Installing profile '$profile' on '$instance' at '$ip'...${Color_Off}"
elif [ $remove == true ]
	then
	echo -e "${BWhite}Uninstalling profile '$profile' on '$instance' at '$ip'...${Color_Off}"
fi

scp -o StrictHostKeyChecking=no -P2266 $filename op@$ip:$filename
echo -e "${BBlue}Deployment Output: ${Blue}"
ssh -p2266 op@$ip "chmod +x $filename && $filename"
echo -e "${Green}"
if [ $remove == false ]
then
	echo "Profile successfully installed on '$instance'!"
else 
	echo "Profile succesfully removed from '$instance'!"
fi
echo -n -e "${Color_Off}"
done
