#!/bin/bash 
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/system-notification.sh"

region="$(jq -r '.region' "$AXIOM_PATH"/axiom.json)"
builder="$(jq -r '.provider' "$AXIOM_PATH"/axiom.json)"
provisioner="full"
start_time=$(date +%s)
op_ssh_password=$(cat /dev/urandom| base64 | head -c 128 | tr -d '+=-' | tr -d '\n' | tr -d /)

# add data to account.json
snapshot_name=axiom-$region-$(date +%s)
account_path=$(ls -la $AXIOM_PATH/axiom.json | rev | cut -d " " -f 1 | rev)
jq '.op="'$op_ssh_password'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
jq '.imageid="'$snapshot_name'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
#


if [ ! -z $1 ]
then
	provisioner="$1"
fi
prov_path="$AXIOM_PATH/images/provisioners/$provisioner.json"
builder_path="$AXIOM_PATH/images/builders/$builder.json"

if [ ! -f "$prov_path" ]
then
	echo -e "${Red}Error: unfortunately, there is no $provisioner_path...${Color_Off}"
	exit
fi
	
if [ ! -f "$builder_path" ]
then
	echo -e "${Red}Error: unfortunately, there is no $builder_path...${Color_Off}"
	exit
fi

image_path="$AXIOM_PATH/images/axiom.json"
"$AXIOM_PATH"/interact/generate_packer "$builder" "$provisioner"

if [[ ! -f "$AXIOM_PATH/configs/authorized_keys" ]]
then
	echo -e "${BRed}You have no authorized keys file at $AXIOM_PATH/configs/authorized_keys"
	echo -e  "Please run 'cat ~/.ssh/id_rsa.pub >> $AXIOM_PATH/configs/authorized_keys' and re-run axiom-build"
	echo -e "You may need to generate a fresh SSH keypair...${Color_Off}"
	exit
fi

cd "$AXIOM_PATH"/ || exit


# change password or fail
if [ -z "$op_ssh_password" ]; then 
echo -e "Unable to generate random password for Packer image.. exiting"
exit 0
fi
#

counter=0
echo -e "${Green}Keep this password for your records: $op_ssh_password${Color_Off}"
echo -e "${BWhite}Building image $provisioner for provider $builder... This can take up to 25 minutes so please be patient!\nOcassionally this will fail, we  don't know why, but it should auto-restart.${Color_Off}"
if packer build -var-file "$AXIOM_PATH"/axiom.json -var "variant=$provisioner" -var "op_random_password=$op_ssh_password" -var "snapshot_name=$snapshot_name" "$image_path";
then
	end_time=$(date +%s)
	seconds="$(expr $end_time - $start_time)"
	time=""
		
	if [[ "$seconds" -gt 59 ]]
	then
		minutes=$(expr $seconds / 60)
		time="$minutes minutes"
	else
		time="$seconds seconds"
	fi

    echo -e "${BGreen}Your build completed successfully in $time! You should run axiom-update && axiom-build weekly to get the latest and greatest updates!" ${Color_Off}"
    echo -e "${Green}To initialize an instance, run axiom-init${Color_Off}"
	  "$AXIOM_PATH"/interact/axiom-prune
    "$NOTIFY_CMD" "Axiom Info" "Build completed successfully! 
else
    counter=$((counter+1))
    echo -e "${BRed}Your build failed :( Please take a look at the errors!${Color_Off}"
    echo -e "${Yellow}This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! ${Color_Off}"
    echo -e "${Yellow}For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues${Color_Off}"
    echo -e "${Green}Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!${Color_Off}"
    "$NOTIFY_CMD" "Axiom Info" "Build failed :("
fi
