#!/bin/bash

snapshot_data=$(doctl compute snapshot list -o json)
image_name="axiom-"

latest_image=$(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | tail -n 1)

for snapshot in $(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | grep -v "$latest_image"); 
do
	echo $snapshot
done

