#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

if [ -z "$1" ]
then
	echo -e "${Red}No instance supplied, use * if you want to delete all instances...${Color_Off}"
    exit
fi

force="false"
query=""
droplets="$(instances)"
selected=""

for var in "$@"; do
	if [ "$var" == "-f" ]; then
		force=true
	fi
done

selected=$(query_instances $@)

if [[ "$selected" ]]
then
	for instance in $selected
	do
	    echo -e "${Red}Deleting '$instance'...${Color_Off}"
		delete_instance "$instance" "$force"
	done
else
	echo -e "${Red}No instance supplied, use * if you want to delete all instances...${Color_Off}"
	exit
fi
#if [[ $query =~ "*" ]]
#then
#    selected=$(echo $droplets | jq -r '.[].name' | grep -E "^$query")
#else
#    selected=$(echo $droplets | jq -r '.[].name' | grep -w "$query")
#fi

#total=$(echo $selected | tr ' ' '\n' | wc -l | awk '{ print $1 }')
#chars=$(echo $selected | wc -c | awk '{ print $1 }')
#if [ $total -eq 1 ]
#then
#    if [ $chars -lt 2 ]
#    then
#	    echo -e "${Red}Instance does not exist..${Color_Off}"
#        exit
#    fi
    
#    selected=$(echo $droplets | jq -r '.[].name' | grep -w "$query")
	
#    echo -e "${Red}Deleting '$selected'...${Color_Off}"
    #delete_instance "$selected" "$force"
#fi
#if [ $total -gt 1 ]
#then
#    i=1
#    for name in $selected
#    do
#	    echo -e "${Red}Deleting '$name'...${Color_Off}"
#        #delete_instance "$name" "$force" &
#        sleep 0.3
#
#        i=$((i+1))
#    done
#fi
