#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

snapshot_data=$(doctl compute snapshot list -o json)
region=$(cat $AXIOM_PATH/axiom.json | jq -r '.region')
image_name="axiom-$region"
latest_image=$(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | tail -n 1)

echo -e "${BWhite}Pruning old Axiom images...${Color_Off}"
echo -e -n "${Blue}"

for snapshot in $(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | grep -v "$latest_image"); 
do
	echo "Deleting '$snapshot'..."
	snapshot_id=$(echo $snapshot_data | jq -r ".[] | select(.name==\"$snapshot\") | .id")
	doctl compute snapshot delete "$snapshot_id" -f
done

echo -e -n "${Color_Off}"
echo -e "${BGreen}Old Snapshots deleted successfully!${Color_Off}"
