#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

instance=$(cat ~/.axiom/profile.json | jq -r '.instance')
ip=$(doctl compute droplet list | grep $instance | awk '{ print $3 }')
restore_box=""

if [ -z "$1" ]
then
	restore_box=$(ls ~/.axiom/boxes/ | fzf)
else
	restore_box="$1"
fi

echo -e "${BWhite}Restoring $restore_box to $instance at $ip ${Color_Off}"
echo -n -e "${Blue}" 

rsync -avzr -e "ssh -p2266" --progress --include-from=$HOME/.axiom/boxes/backup-files.txt ~/.axiom/boxes/"$restore_box"/ op@"$ip":~/

echo -n -e "${Color_Off}" 
echo -e "${BGreen}Restore of '$restore_box' to '$instance' successful!${Color_Off}" 
