#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"

if [ -z $1 ]; then
	data=$(doctl compute droplet list -o json)
	i=0
	for f in $(echo $data | jq -r '.[].size.price_monthly'); do new=$(expr $i +  $f); i=$new; done
	(echo "Instance,IP,Region,Memory,\$/M" && echo $data | jq  -r '.[] | [.name, .networks.v4[].ip_address, .region.slug, .size_slug, .size.price_monthly] | @csv' && echo "_,_,Total,\$$i") | sed 's/"//g' | column -t -s, | perl -pe '$_ = "\033[0;37m$_\033[0;34m" if($. % 2)'
else
	if [[ "$1" == "--json" ]]; then
		doctl compute droplet list -o json | jq
	else
		resp=$(doctl compute droplet list | awk '{ print $2 }' | grep -v "Name" | grep -E "$1")
		count=$(echo $resp | tr ' ' '\n' | wc -l | awk '{ print $1 }')

		if [[ "$count" -gt 1 ]]; then
			i=1
			for name in $resp; do
				echo "$i:$name"
				i=$((i + 1))
			done
		else
			doctl compute droplet list | grep -E $1 | awk '{ print $3 }'
		fi
	fi
fi

$AXIOM_PATH/interact/header.sh
