#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

instances="$(query_instances "$2")"
username="$1"

command="curl -s https://github.com/$username.keys >> ~/.ssh/authorized_keys"

$AXIOM_PATH/interact/axiom-ssh --just-generate

for instance in $instances
do
	 $AXIOM_PATH/interact/axiom-exec "$command" "$instance" --cache 
done
