#!/bin/bash

Color_Off='\033[0m'       # Text Reset
Red='\033[0;31m'  

name=$1
#domain=$(cat ~/.axiom.json| jq -r '.domain')
if [ -z "$1" ]
then
    ans=$(doctl compute droplet list | awk '{ print $2 }' | grep -v "Name" | fzf)
#    doctl compute domain records delete $domain $(doctl compute domain records list $domain | grep $ans | awk '{ print $1 }')
	echo -e "${Red}Deleting '$ans'...${Color_Off}"
    doctl compute droplet delete $ans
    echo "{\"instance\":\"false\"}" | jq > ~/.axiom/profile.json
else
    doctl compute droplet delete $1
    echo -e "${Red}Deleting '$1'...${Color_Off}"
    echo "{\"instance\":\"false\"}" | jq > ~/.axiom/profile.json
#    doctl compute domain records delete $domain $(doctl compute domain records list $domain | grep $1 | awk '{ print $1 }')
fi

