#!/usr/bin/env bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White

if [ ! -z "$1" ]
then
	case $1 in
	ls*)
		if [[ "$2" == "--archive" ]]
		then
			echo -e "${BWhite}Archived Boxes${Color_Off}"
			echo -n -e "${Blue}"
			ls -l ~/.axiom/archive/ | sed 's/.tar.gz.gpg//g' | awk '{ print $9 " " $6 " " $7 " " $8 }' | column -t
			echo -n -e "${Color_Off}"
		else
			echo -e "${BWhite}Available Backup Boxes${Color_Off}"
			echo -n -e "${Blue}"
			ls -l  ~/.axiom/boxes/ | grep -v "backup-files.txt" | awk '{ print $9 " " $6 " " $7 " " $8 }' | column -t
			echo -n -e "${Color_Off}"
		fi
		;;
	cd*)
		box_path="$HOME/.axiom/boxes/$2"

		if [ -d "$box_path" ]
		then
			echo -e "${BWhite}Changing directory to box '$2'...${Color_Off}"
		
			cd "${box_path}"
			exec $SHELL
		else
			echo -e  "${BRed}Box doesn't exist${Color_Off}"
		fi
		;;
	rm*)
		box_path="$HOME/.axiom/boxes/$2"

		if [ -d "$box_path" ]
		then
			echo -e "${BWhite}Deleting box backup '$2'...${Color_Off}"
			rm -rf "$box_path"
		else
			echo -e  "${BRed}Box doesn't exist${Color_Off}"
		fi

		;;
	new*)
		box_path="$HOME/.axiom/boxes/$2"

		if [ ! -d "$box_path" ]
		then
			echo -e "${BWhite}Creating box '$2'...${Color_Off}"
			mkdir -p "$box_path/work"
            cp ~/.axiom/configs/oh-my-zsh.tar.gz $box_path/.oh-my-zsh.tar.gz
            cd $box_path/ && tar -xf .oh-my-zsh.tar.gz
		else
			echo -e "${BRed}Box already exists${Color_Off}"
		fi
		;;
	cp*)
		box_path="$HOME/.axiom/boxes/$2"

		if [ -d "$box_path" ]
		then
			echo -e "${BWhite}Coping box '$2' to '$3'${Color_Off}"
			cp -r $box_path "$HOME/.axiom/boxes/$3"
		fi
		;;
	get*)
		repo="https://github.com/$2.git"
		box=$(echo $2 | sed 's/\//-/g')
		echo -e "${BWhite}Cloning box: $2${Color_Off}"
        clone_path="$HOME/.axiom/boxes/$box"

        if [ ! -d $clone_path ]
        then
		    git clone $repo $clone_path
        else
            cd $clone_path && git pull 
        fi
        ;;
    update*)
		box=$(echo $2 | sed 's/\//-/g')
        cd ~/.axiom/boxes/$box && git pull 
        ;;
    archive*)
		box="$2"
		email="$(cat $HOME/.axiom/axiom.json |  jq -r '.email?')"

		if [[ "$email" != "null" ]]
		then

			if [ -d "$HOME/.axiom/boxes/$box/" ]
			then
				echo -e "${BWhite}Archiving $box...${Color_Off}${Blue}"
				cd ~/.axiom/boxes/
				tar -czf "$box.tar.gz" $box
				rm -rf $box
				gpg -r "$email" -e "$box.tar.gz"
				rm "$box.tar.gz"
				mv "$box.tar.gz.gpg" "$HOME/.axiom/archive/"
				echo -e "${BWhite}Archived $box successfully...${Color_Off}"
			else
				echo -e "${Red}Box does not exist...${Color_Off}"
			fi
		else
			echo -e "${BWhite}GPG is not configured within axiom, would you like to set it up?${Color_Off}"
			echo -e -n "${Blue}y/n: ${Color_Off}"
			read ans

			if [[ "$ans" == "y" ]]
			then
				echo -e "${BBlue}You have two choices... \n1) Generate a new key just for axiom (default)\n2) Use an existing key (manual)${Color_Off}"
				echo -e -n "${Blue}>> ${Color_Off}"
				read option
				
				if [[ "$option" -eq 1 ]]
				then
					echo -e "${Blue}Generating new gpg key...${Color_Off}"
					gpg --gen-key
					email=$(gpg --list-secret-keys | grep uid | tail -n1 |  grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
					echo -e "${Blue}Generated key for $email!${Color_Off}"
					echo -e "${Blue}Please try the archive feature again now!${Color_Off}"
					cat $HOME/.axiom/axiom.json | jq -r ".email |= \"$email\"" | jq > $HOME/.axiom/axiom.json.new
					mv $HOME/.axiom/axiom.json.new $HOME/.axiom/axiom.json
				elif [[ "$option" -eq 2 ]]
				then
					echo -e -n "${Blue}Please enter your GPG recipient email: ${Color_Off}"
					read email
					cat $HOME/.axiom/axiom.json | jq -r ".email |= \"$email\"" | jq
				fi
			fi
		fi

		;;
	unarchive*)
		box="$2"
		echo -e "${BWhite}Unarchiving $box...${Color_Off}${Blue}"
		if [ -f "$HOME/.axiom/archive/$box.tar.gz.gpg" ]
		then
			cd ~/.axiom/archive/
			gpg -o "$box.tar.gz" -d "$box.tar.gz.gpg"
			rm "$box.tar.gz.gpg"
			tar -xf "$box.tar.gz"
			rm "$box.tar.gz"
			mv "$box" "$HOME/.axiom/boxes/"
			echo -e "${BWhite}Unarchived $box successfully...${Color_Off}"
		else
			echo -e "${Red}Box is not archived.${Color_Off}"
		fi
		;;

	*)
		echo "Command '$1' not found..."
		;;
	esac

else
	echo -e "Usage:\n\t axiom-boxes ls\n\t axiom-boxes new <BOX>\n\t axiom-boxes cd <BOX> \n\t axiom-boxes get user/repo"
fi
