#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White


if [ -z "$1" ]
then
    instance=$(cat ~/.axiom/profile.json | jq -r '.instance')
    ip=$(doctl compute droplet list | grep $instance | awk '{ print $3 }')
	ans=$(ls ~/.axiom/boxes/ | fzf)
	echo -e "${BWhite}Restoring $ans to $instance at $ip ${Color_Off}"
	echo -n -e "${Blue}" 
    rsync -avz -e "ssh -p2266" --progress ~/.axiom/boxes/$ans/.* op@$ip:~/
    rsync -avz -e "ssh -p2266" --progress ~/.axiom/boxes/$ans/* op@$ip:~/
	ssh -p2266 op@"$ip" "tar -xvf .dotfiles.backup.tar.gz && tar -xvf .go.backup.tar.gz"
	echo -n -e "${Color_Off}" 
	echo -e "${BGreen}Restore of '$ns' to '$instance' successful!${Color_Off}" 
else
    instance=$(cat ~/.axiom/profile.json | jq -r '.instance')
    ip=$(doctl compute droplet list | grep $instance | awk '{ print $3 }')
	echo -e "${BWhite}Restoring $1 to $instance at $ip ${Color_Off}"
	echo -n -e "${Blue}" 
    rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress "~/.axiom/boxes/$1/*" op@$ip:~/
    rsync -avz -e "ssh -p2266 -o StrictHostKeyChecking=no" --progress "~/.axiom/boxes/$1/.*" op@$ip:~/
	ssh -p2266 op@"$ip" "tar -xvf .dotfiles.backup.tar.gz && tar -xvf .go.tar.gz"
	echo -n -e "${Color_Off}" 
	echo -e "${BGreen}Restore of '$1' to '$instance' successful!${Color_Off}" 
fi

