#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White

snapshot_data=$(doctl compute snapshot list -o json)
image_name="axiom-"
latest_image=$(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | tail -n 1)

echo -e "${BWhite}Pruning old Axiom images...${Color_Off}"
echo -e -n "${Blue}"

for snapshot in $(echo $snapshot_data | jq -r '.[].name' | grep "$image_name" | grep -v "$latest_image"); 
do
	echo "Deleting '$snapshot'..."
	snapshot_id=$(echo $snapshot_data | jq -r ".[] | select(.name==\"$snapshot\") | .id")
	doctl compute snapshot delete "$snapshot_id" -f
done

echo -e -n "${Color_Off}"
echo -e "${BGreen}Old Snapshots deleted successfully!${Color_Off}"
