#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

instance=$(cat $AXIOM_PATH/profile.json | jq -r '.instance')
ip=$(instance_ip $instance)

export DOCKER_HOST=ssh://op@$ip:2266
