#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

gen_name=""

if [ -z $1 ] || [[ $1 =~ "-i" ]] || [[ $1 =~ "-t" ]] 
then
    gen_name="${names[$RANDOM % ${#names[@]} ]}"
else
    if [ ! -z $1 ]
    then
        gen_name="$1"
    fi
fi

spend=false
hours=false
amount=false
prompt=false
region=false

for var in "$@"
do
    if [[ "$var" =~ "-t" ]]
    then
        hours="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        #echo -e "${BWhite}Setting expiry to $hours hours${Color_Off}"
    fi
    if [[ "$var" =~ "-i" ]]
    then
        amount="$(echo "$var" | sed 's/=/ /g' | awk '{ print $2 }')"
        #echo -e "${BWhite}Setting number of instances to $amount...${Color_Off}"
    fi
	if [[ "$var" =~ "-r" ]]
    then
		regions=$(snapshots | jq -r '.[] | select(.name | contains("axiom")) | .name'  | cut -d "-" -f 2 | sort -u)
    fi
done


if [ "$hours" == "false" ]
then
    hours=1
fi

if [ "$amount" == "false" ]
then
	amount=3
fi

echo -e "${BWhite}Initializing new fleet '$gen_name' with $amount instances...${Color_Off}"
sizes=$(instance_sizes)
slug="s-1vcpu-1gb"
instance_data=$(echo $sizes | jq ".[] | select(.slug==\"$slug\")")
price_hourly=$(echo $instance_data | jq .price_hourly)
cores=$(echo $instance_data | jq .vcpus)
mem_big=$(echo $instance_data | jq .memory)
mem=$(expr $mem_big / 1024)
disk=$(echo $instance_data | jq .disk)
total=$(bc <<< "scale=2; $price_hourly * $hours * $amount")
total_rounded=$(echo "scale=3; price=$total; scale=2; price/1 " | bc | sed 's/^\./0./')
total_spend_per_instance=$(bc <<< "scale=2; $price_hourly * $hours")
total_spend_per_instance_rounded=$(echo "scale=3; price=$total_spend_per_instance; scale=4; price/1 " | bc | sed 's/^\./0./')
echo -e "${Green}Total estimated cost: \$$total_rounded${Color_Off}"
echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"


sleep 4

expiry=$(bc <<< "scale=2; $hours * 60")
expiry=$(bc <<< "scale=2; $expiry - 8")
time=120

for i in $(seq -f "%02g" 1 $amount)
do
   time=$((time+2))
   name="$gen_name$i"
   echo -e "${BWhite}Initializing $name for $hours hours... This instance will cost: \$$total_spend_per_instance_rounded"
   $AXIOM_PATH/interact/axiom-init $name --quiet --size=$slug --expire=$expiry &
   sleep 0.7
done

while [ $time -gt 0 ]; do
    echo -ne ">> T-Minus $time to fleet $gen_name initialization...\033[0K\r"
    sleep 1
    : $((time--))
done

echo -e "${BGreen}Fleet started succesfully! All instances will automatically implode after $expiry minutes or $hours hours. To extend the lifetime on an instance, set-expiry.sh \"10 hours\" etc.${Color_Off}" 
