#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/do-functions.sh"

lsplit() {
	src="$1"
	instances=$2
	total=$(echo $instances|  tr ' ' '\n' | wc  -l | awk '{ print $1 }')
	orig_pwd=$(pwd)

	lines=$(wc -l $src | awk '{ print $1 }')
	lines_per_file=$(bc <<< "scale=2; $lines / $total" | awk '{print int($1+0.5)}')
	id=$(echo "$instances" | md5sum | awk '{ print $1 }' |  head -c5)
	split_dir="$AXIOM_PATH/tmp/$id"

	rm  -rf $split_dir  >> /dev/null  2>&1
	mkdir -p $split_dir
	cp $src $split_dir

	cd $split_dir
	split -l $lines_per_file $src
	rm $src
	a=1

	for f in $(ls | grep x)
	do
		mv $f $a.txt
		a=$((a+1))
	done

	i=1
	for instance in $(echo $instances | tr ' ' '\n')
	do
		mv $i.txt $instance.txt
		i=$((i+1))
	done
	
	cd $orig_pwd
	echo -n $split_dir
}

#Load fromthe  module
module="modules/masscan.json"
cmd=$(jq -r '.command'  $module)
box_infile=$(jq -r '.box_infile'  $module)
box_outfile=$(jq -r '.box_outfile'  $module)
ports=$(jq -r '.default_ports'  $module)
args=$(jq -r '.default_args'  $module)

# hostoptions
targets_infile=""
query="$1"
outfile="$(echo $query | sed 's/\*//g')-$(date +%s).txt"

# Set user input
for var in "$@"
do
	if [[ "$var" =~ "-p" ]]
	then
		ports=$(echo $var | sed 's/-p//g')
	fi
	if [[ "$var" =~  "-iL=" ]]
	then
		targets_infile=$(echo "$var" | cut -d "=" -f2)
	fi
done

if [[ ! -f $targets_infile ]]
then
	echo "File doesn't exist."
	exit
fi

instances=$(query_instances "$1")

if [ "$instances" ]
then
	src_prefix=$(lsplit $targets_infile "$instances")
	axiom-scp "$src_prefix/\$name.txt" "$query:$box_infile"
	cmd_rendered=$(echo $cmd | sed "s/\$ports/$ports/g" | sed "s/\$args/$args/g" | sed "s/\$infile/$box_infile/g"  | sed "s/\$outfile/$box_outfile/g")
	echo  $instances | tr ' ' '\n' > $src_prefix/hosts.txt
	
	total=$(wc -l $src_prefix/hosts.txt | awk '{ print $1 }')
	interlace -tL $src_prefix/hosts.txt -threads $total -c "axiom-exec '$cmd_rendered' '_target_' -q" -vv
	axiom-scp "$query:$box_outfile" "$src_prefix/\$name-out.txt"
	cat $src_prefix/$query-out.txt | sort -u > $outfile
	echo "File saved to $outfile."
else
	echo "No instances in that fleet, use 'axiom-fleet -i=7 -t=2' to spin up a fleet"
fi


