
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export GOPATH=/home/op/go
export PS1='\[\033[01;32m\]$(whoami)@$(hostname) \[\033[0m\]'
alias ls="ls --color=auto"
