#!/bin/bash

msg() {
    bot_id=$(cat ~/.telegram.json | jq -r .bot_id)
    chat_id=$(cat ~/.telegram.json | jq -r .chat_id)
    msg="$1"

    curl -X POST -H 'Content-Type: application/json' -d "{\"chat_id\": \"$chat_id\", \"text\": \"$msg\"}" https://api.telegram.org/bot$bot_id/sendMessage
}

if [[ "$1" == "--init" ]]
then
    echo -n "Please enter your bot id: "
    read bot_id
    echo -n "Please enter your chat id: "
    read chat_id
    echo "{\"bot_id\":\"$bot_id\", \"chat_id\":\"$chat_id\"}"> ~/.telegram.json
else
    msg "$1"
fi

