#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White

msg() {
    bot_id=$(cat /home/op/.telegram.json | jq -r .bot_id)
    chat_id=$(cat /home/op/.telegram.json | jq -r .chat_id)
    msg="$1"

    ans=$(curl -s -X POST -H 'Content-Type: application/json' -d "{\"chat_id\": \"$chat_id\", \"text\": \"$msg\"}" https://api.telegram.org/bot$bot_id/sendMessage)
    username=$(echo $ans | jq -r '.result.chat.username')
    echo -e "${BGreen}Message sent to '$username'!"
}

if [[ "$1" == "--init" ]]
then
    echo -n "Please enter your bot id: "
    read bot_id
    echo -n "Please enter your chat id: "
    read chat_id
    echo "{\"bot_id\":\"$bot_id\", \"chat_id\":\"$chat_id\"}"> /home/op/.telegram.json
    sudo chown -R op:users /home/op/.telegram.json
else
    msg "$1"
fi

