export TERM="xterm-256color"

function bin2sc {
    # convert .bin to shellcode
    hexdump -v -e '"\\""x" 1/1 "%02x" ""' ${1}
}

export ZSH=/home/op/.oh-my-zsh

ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(dircycle github z autojump rails archlinux zsh-navigation-tools docker vagrant cp ruby)
source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.rvm/bin:/home/op/go/bin" # Add RVM to PATH for scripting
source ~/.profile

POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_IP_BACKGROUND='black'
POWERLEVEL9K_IP_FOREGROUND='white'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='white'

function dockershell() {
    docker run --rm -i -t --entrypoint=/bin/bash "$@"
}

function dockershellsh() {
    docker run --rm -i -t --entrypoint=/bin/sh "$@"
}

function dockershellhere() {
    dirname=${PWD##*/}
    docker run --rm -it --entrypoint=/bin/bash -v `pwd`:/${dirname} -w /${dirname} "$@"
}

function dockershellshhere() {
    docker run --rm -it --entrypoint=/bin/sh -v `pwd`:/${dirname} -w /${dirname} "$@"
}

function dockerwindowshellhere() {
    dirname=${PWD##*/}
    docker -c 2019-box run --rm -it -v "C:${PWD}:C:/source" -w "C:/source" "$@"
}

impacket() {
    docker run --rm -it rflathers/impacket "$@"
}

smbservehere() {
    local sharename
    [[ -z $1 ]] && sharename="SHARE" || sharename=$1
    docker run --rm -it -p 445:445 -v "${PWD}:/tmp/serve" rflathers/impacket smbserver.py -smb2support $sharename /tmp/serve
}

nginxhere() {
    docker run --rm -it -p 80:80 -p 443:443 -v "${PWD}:/srv/data" rflathers/nginxserve
}

webdavhere() {
    docker run --rm -it -p 80:80 -v "${PWD}:/srv/data/share" rflathers/webdav
}

metasploit() {
    docker run --rm -it  --network=host metasploitframework/metasploit-framework ./msfconsole "$@"
}

metasploitports() {
    docker run --rm -it -v "${HOME}/.msf4:/home/msf/.msf4" -p 8443-8500:8443-8500 metasploitframework/metasploit-framework ./msfconsole "$@"
}

msfvenomhere() {
    docker run --rm -it -v "${HOME}/.msf4:/home/msf/.msf4" -v "${PWD}:/data" metasploitframework/metasploit-framework ./msfvenom "$@"
}

reqdump() {
    docker run --rm -it -p 80:3000 rflathers/reqdump
}

postfiledumphere() {
    docker run --rm -it -p80:3000 -v "${PWD}:/data" rflathers/postfiledump
}



export EDITOR='vim'
export GOPATH=/home/op/tmp/golang/ 
export TERM="xterm-256color"
export HOME=/home/op


export BIG="/home/op/lists/seclists/Discovery/Web-Content/big.txt"
export WEB="/home/op/lists/seclists/Discovery/Web-Content/"
export DIRS_LARGE=/home/op/lists/seclists/Discovery/Web-Content/raft-large-directories.txt
export DIRS_SMALL=/home/op/lists/seclists/Discovery/Web-Content/raft-small-directories.txt
export FILES_LARGE=/home/op/lists/seclists/Discovery/Web-Content/raft-large-files.txt
export FILES_SMALL=/home/op/lists/seclists/Discovery/Web-Content/raft-small-files.txt


alias ls=" ls --color -sh"
alias ping="prettyping --nolegend"
alias wclone="wget -H -p -k"

